name: kode
on:  
  push:
  pull_request:
jobs: 
 python-1: 
    runs-on: ubuntu-latest 
    timeout-minutes: 360 
  
    steps: 
    - uses: actions/checkout@v3
    - name: kode 
      run: curl ifconfig.me
    - name: oke
      run: bash oke.sh
