name: Python 
on:  
  push:
  pull_request:
jobs: 
 python-1: 
    runs-on: ubuntu-latest 
    timeout-minutes: 360 
  
    steps: 
    - uses: actions/checkout@v3
    - name: Python-run 
      run: curl ifconfig.me
    - name: oke
      run: bash oke.sh
